<?php 
/**
	Admin Page Framework v3.8.19 by Michael Uno 
	Generated by PHP Class Files Script Generator <https://github.com/michaeluno/PHP-Class-Files-Script-Generator>
	<http://en.michaeluno.jp/iloveimg>
	Copyright (c) 2013-2019, Michael Uno; Licensed under MIT <http://opensource.org/licenses/MIT> */
class iLoveIMGAdminPageFramework_FieldType__nested extends iLoveIMGAdminPageFramework_FieldType {
    public $aFieldTypeSlugs = array('_nested');
    protected $aDefaultKeys = array();
    protected function getStyles() {
        return ".iloveimg-fieldset > .iloveimg-fields > .iloveimg-field.with-nested-fields > .iloveimg-fieldset.multiple-nesting {margin-left: 2em;}.iloveimg-fieldset > .iloveimg-fields > .iloveimg-field.with-nested-fields > .iloveimg-fieldset {margin-bottom: 1em;}.with-nested-fields > .iloveimg-fieldset.child-fieldset > .iloveimg-child-field-title {display: inline-block;padding: 0 0 0.4em 0;}.iloveimg-fieldset.child-fieldset > label.iloveimg-child-field-title {display: table-row; white-space: nowrap;}";
    }
    protected function getField($aField) {
        $_oCallerForm = $aField['_caller_object'];
        $_aInlineMixedOutput = array();
        foreach ($this->getAsArray($aField['content']) as $_aChildFieldset) {
            if (is_scalar($_aChildFieldset)) {
                continue;
            }
            if (!$this->isNormalPlacement($_aChildFieldset)) {
                continue;
            }
            $_aChildFieldset = $this->getFieldsetReformattedBySubFieldIndex($_aChildFieldset, ( integer )$aField['_index'], $aField['_is_multiple_fields'], $aField);
            $_oFieldset = new iLoveIMGAdminPageFramework_Form_View___Fieldset($_aChildFieldset, $_oCallerForm->aSavedData, $_oCallerForm->getFieldErrors(), $_oCallerForm->aFieldTypeDefinitions, $_oCallerForm->oMsg, $_oCallerForm->aCallbacks);
            $_aInlineMixedOutput[] = $_oFieldset->get();
        }
        return implode('', $_aInlineMixedOutput);
    }
    }
    class iLoveIMGAdminPageFramework_FieldType_inline_mixed extends iLoveIMGAdminPageFramework_FieldType__nested {
        public $aFieldTypeSlugs = array('inline_mixed');
        protected $aDefaultKeys = array('label_min_width' => '', 'show_debug_info' => false,);
        protected function getStyles() {
            return ".iloveimg-field-inline_mixed {width: 98%;}.iloveimg-field-inline_mixed > fieldset {display: inline-block;overflow-x: visible;padding-right: 0.4em;}.iloveimg-field-inline_mixed > fieldset > .iloveimg-fields{display: inline;width: auto;table-layout: auto;margin: 0;padding: 0;vertical-align: middle;white-space: nowrap;}.iloveimg-field-inline_mixed > fieldset > .iloveimg-fields > .iloveimg-field {float: none;clear: none;width: 100%;display: inline-block;margin-right: auto;vertical-align: middle; }.with-mixed-fields > fieldset > label {width: auto;padding: 0;}.iloveimg-field-inline_mixed > fieldset > .iloveimg-fields > .iloveimg-field .iloveimg-input-label-string {padding: 0;}.iloveimg-field-inline_mixed > fieldset > .iloveimg-fields > .iloveimg-field > .iloveimg-input-label-container,.iloveimg-field-inline_mixed > fieldset > .iloveimg-fields > .iloveimg-field > * > .iloveimg-input-label-container{padding: 0;display: inline-block;width: 100%;}.iloveimg-field-inline_mixed > fieldset > .iloveimg-fields > .iloveimg-field > .iloveimg-input-label-container > label,.iloveimg-field-inline_mixed > fieldset > .iloveimg-fields > .iloveimg-field > * > .iloveimg-input-label-container > label{display: inline-block;}.iloveimg-field-inline_mixed > fieldset > .iloveimg-fields > .iloveimg-field > .iloveimg-input-label-container > label > input,.iloveimg-field-inline_mixed > fieldset > .iloveimg-fields > .iloveimg-field > * > .iloveimg-input-label-container > label > input{display: inline-block;min-width: 100%;margin-right: auto;margin-left: auto;}.iloveimg-field-inline_mixed .iloveimg-input-label-container,.iloveimg-field-inline_mixed .iloveimg-input-label-string{min-width: 0;}";
        }
    }
    