<?php 
/**
	Admin Page Framework v3.8.19 by Michael Uno 
	Generated by PHP Class Files Script Generator <https://github.com/michaeluno/PHP-Class-Files-Script-Generator>
	<http://en.michaeluno.jp/iloveimg>
	Copyright (c) 2013-2019, Michael Uno; Licensed under MIT <http://opensource.org/licenses/MIT> */
class iLoveIMGAdminPageFramework_Form_View___CSS_term_meta extends iLoveIMGAdminPageFramework_Form_View___CSS_Base {
    protected function _get() {
        return $this->_getRules();
    }
    private function _getRules() {
        return ".iloveimg-form-table-outer-row-term_meta,.iloveimg-form-table-outer-row-term_meta > td {margin: 0;padding: 0;}.iloveimg-form-table-term_meta > tbody > tr > td {margin-left: 0;padding-left: 0;}.iloveimg-form-table-term_meta .iloveimg-sectionset,.iloveimg-form-table-term_meta .iloveimg-section {margin-bottom: 0;}.iloveimg-form-table-term_meta.add-new-term .title-colon {margin-left: 0.2em;}.iloveimg-form-table-term_meta.add-new-term .iloveimg-section .form-table > tbody > tr > td,.iloveimg-form-table-term_meta.add-new-term .iloveimg-section .form-table > tbody > tr > th{display: inline-block;width: 100%;padding: 0;float: right;clear: right;}.iloveimg-form-table-term_meta.add-new-term .iloveimg-field {width: auto;}.iloveimg-form-table-term_meta.add-new-term .iloveimg-field {max-width: 100%;}.iloveimg-form-table-term_meta.add-new-term .sortable .iloveimg-field {width: auto;} .iloveimg-form-table-term_meta.add-new-term .iloveimg-section .form-table > tbody > tr > th {font-size: 13px;line-height: 1.5;margin: 0;font-weight: 700;}.iloveimg-form-table-term_meta .iloveimg-section-title h3 {border: none;font-weight: bold;font-size: 1.12em;margin: 0;padding: 0;font-family: 'Open Sans', sans-serif; cursor: inherit; -webkit-user-select: inherit;-moz-user-select: inherit;user-select: inherit;}.iloveimg-form-table-term_meta .iloveimg-collapsible-title h3 {margin: 0;}.iloveimg-form-table-term_meta h4 {margin: 1em 0;font-size: 1.04em;}.iloveimg-form-table-term_meta .iloveimg-section-tab h4 {margin: 0;} ";
    }
    }
    