<?php 
/**
	Admin Page Framework v3.8.19 by Michael Uno 
	Generated by PHP Class Files Script Generator <https://github.com/michaeluno/PHP-Class-Files-Script-Generator>
	<http://en.michaeluno.jp/iloveimg>
	Copyright (c) 2013-2019, Michael Uno; Licensed under MIT <http://opensource.org/licenses/MIT> */
class iLoveIMGAdminPageFramework_Form_View___Script_OptionStorage extends iLoveIMGAdminPageFramework_Form_View___Script_Base {
    static public function getScript() {
        return <<<JAVASCRIPTS
(function ( $ ) {
            
    $.fn.aiLoveIMGAdminPageFrameworkInputOptions = {}; 
                            
    $.fn.storeiLoveIMGAdminPageFrameworkInputOptions = function( sID, vOptions ) {
        var sID = sID.replace( /__\d+_/, '___' );	// remove the section index. The g modifier is not used so it will replace only the first occurrence.
        $.fn.aiLoveIMGAdminPageFrameworkInputOptions[ sID ] = vOptions;
    };	
    $.fn.getiLoveIMGAdminPageFrameworkInputOptions = function( sID ) {
        var sID = sID.replace( /__\d+_/, '___' ); // remove the section index
        return ( 'undefined' === typeof $.fn.aiLoveIMGAdminPageFrameworkInputOptions[ sID ] )
            ? null
            : $.fn.aiLoveIMGAdminPageFrameworkInputOptions[ sID ];
    }

}( jQuery ));
JAVASCRIPTS;
        
    }
    }
    